name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: publish
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /bin/make
