name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: remake
        run: |
          docker run -v $(pwd):/data -w /data pandoc/core:2.9 make
